version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - laravel_local
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 12345678
    networks:
      - laravel_local
  pgsql:
    image: postgres:latest
    container_name: pgsql
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: laravel
    networks:
      - laravel_local
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel_local
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: laravel
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./minio:/bitnami/minio/data
    networks:
      - laravel_local
networks:
  laravel_local:
    driver: bridge
